spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
        registration:
          google:
            client-id: 254413885788-mbl7g2mt0c35meg2ev7eofpjknpohuvq.apps.googleusercontent.com
            client-secret: AQtsQrk7vsDSSS5FvB00v3ez
            scope: profile,email
          naver:
            client-id: CQ5z7EJHqFRJs9b_VPns
            client-secret: K6MyZR5Qxg
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            scope: name,email,profile_image
            client-name: Naver


